<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE badges [
  <!ELEMENT badges (badge*)>
  <!ELEMENT badge (name,description,levels)>
  
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  
  <!ELEMENT levels (availability+)>
  <!ELEMENT availability (#PCDATA)>

  <!ATTLIST badge id ID #REQUIRED>
  <!ATTLIST badge type (activity|development) "activity">
  <!ATTLIST availability level (beaver | cub | scout) "beaver">
]>

<badges>
  <badge id="s1">
    <name>Climbing</name>
    <description>This badge is awarded to scouts who have shown a proficiency in climbing</description>
    <levels>
      <availability level="beaver">Not Available</availability>
      <availability level ="cub">Available</availability>
      <availability level="scout">Available</availability>
    </levels>
  </badge>

  <badge id="s2">
    <name>Abseiling</name>
    <description>This badge is awarded to scouts who have shown a proficiency in abseiling</description>
    <levels>
      <availability level="beaver">Not Available</availability>
      <availability level ="cub">Not Available</availability>
      <availability level="scout">Available</availability>
    </levels>
  </badge>

  <badge id="s3">
    <name>Archery</name>
    <description>This badge is awarded to scouts who have managed to show that they can use a modern bow in a safe manner</description>
    <levels>
      <availability level="beaver">Available</availability>
      <availability level ="cub">Available</availability>
      <availability level="scout">Available</availability>
    </levels>
  </badge>

  <badge id="s4">
    <name>Football</name>
    <description>This badge is awarded to scouts who have shown a range of skills in football</description>
    <levels>
      <availability level="beaver">Available</availability>
      <availability level ="cub">Available</availability>
      <availability level="scout">Available</availability>
    </levels>
  </badge>

  <badge id="s5">
    <name>Swimming</name>
    <description>This badge is awarded to scouts who have shown a proficiency in swimming</description>
    <levels>
      <availability level="beaver">Available</availability>
      <availability level ="cub">Available</availability>
      <availability level="scout">Available</availability>
    </levels>
  </badge>

  <badge id="s6" type="development">
    <name>Computing</name>
    <description>This badge is awarded to scouts who have shown a proficiency in computing</description>
    <levels>
      <availability level="beaver">Available</availability>
      <availability level ="cub">Available</availability>
      <availability level="scout">Available</availability>
    </levels>
  </badge>

  <badge id="s7" type="development">
    <name>Web Development</name>
    <description>This badge is awarded to scouts who have managed to creat a web page that is appropriate to the level</description>
    <levels>
      <availability level="beaver">Available</availability>
      <availability level ="cub">Available</availability>
      <availability level="scout">Available</availability>
    </levels>
  </badge>

  <badge id="s8" type="activity">
    <name>Gliding</name>
    <description>This badge is awarded to scouts who have shown a proficiency in gliding</description>
    <levels>
      <availability level="beaver">Not Available</availability>
      <availability level ="cub">Not Available</availability>
      <availability level="scout">Available</availability>
    </levels>
  </badge>

  <badge id="s9" type="development">
    <name>Religious Knowledge</name>
    <description>This badge is awarded to scouts who have shown a proficiency in religious knowledge</description>
    <levels>
      <availability level="beaver">Available</availability>
      <availability level ="cub">Available</availability>
      <availability level="scout">Available</availability>
    </levels>
  </badge>
  
  <badge id="s10" type="development"> 
    <name>First Aid</name>
    <description>This badge is warded to scouts who have shown a proficiency in first aid</description>
    <levels>
      <availability level="beaver">Available</availability>
      <availability level ="cub">Available</availability>
      <availability level="scout">Available</availability>
    </levels>
  </badge>

  <badge id="s11" type="development">
    <name>Promise</name>
    <description>This badge is warded to scouts who have shown that they have learned and understood the scout promise</description>
    <levels>
      <availability level="beaver">Available</availability>
      <availability level ="cub">Available</availability>
      <availability level="scout">Available</availability>
    </levels>
  </badge>

  <badge id="s12" type="development">
    <name>Cooking</name>
    <description>This badge is warded to scouts who have shown a proficiency in cooking</description>
    <levels>
      <availability level="beaver">Available</availability>
      <availability level ="cub">Available</availability>
      <availability level="scout">Available</availability>
    </levels>
  </badge>
  
  
</badges>
